version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app # Mount the entire project (including shared package.json)
      - frontend-node_modules:/app/node_modules # Named volume for node_modules
      - ./apps/frontend:/app/apps/frontend # Bind mount for frontend code
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    command: pnpm dev:frontend # Runs NX script

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile.dev
    ports:
      - '3001:3001'
    volumes:
      - .:/app # Mount the entire project (including shared package.json)
      - backend-node_modules:/app/node_modules # Named volume for node_modules
      - ./apps/backend:/app/apps/backend # Bind mount for backend code
    command: pnpm dev:backend # Runs NX script
volumes:
  frontend-node_modules:
  backend-node_modules:
