version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: pnpm dev:frontend # Runs NX script

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile.dev
    ports:
      - '3001:3001'
      - '8080:8080'
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm dev:backend # Runs NX script
